"""
properties.py — Saturation thermophysical properties via CoolProp.

Supported fluids for PINN-ONB01 Phase 1:
    water, R-123, R-134a          — directly via CoolProp
    FC-72, FC-77                  — NOT supported by CoolProp 7.2; raises UnsupportedFluidError
    HFE-7100                      — NOT supported by CoolProp 7.2; raises UnsupportedFluidError
    Novec649 (FC-5112)            — supported via CoolProp identifier "Novec649"

Units: all SI throughout.
    P       [Pa]
    T       [K]
    rho     [kg/m^3]
    sigma   [N/m]
    h_fg    [J/kg]
    mu      [Pa·s]
    k       [W/(m·K)]
    cp      [J/(kg·K)]
    nu      [m^2/s]
    r_c     [m]
    L_c     [m]

Reference values for validation (water, 1 atm = 101 325 Pa):
    T_sat   = 373.124 K
    rho_l   = 958.4  kg/m^3
    sigma   = 0.0589 N/m
    h_fg    = 2.257e6 J/kg

Authors: PINN-ONB01 project (auto-generated by properties agent)
Date   : 2026-05-10
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from functools import lru_cache

import CoolProp.CoolProp as _CP

# ---------------------------------------------------------------------------
# Fluid name mapping: project identifier -> CoolProp identifier
# ---------------------------------------------------------------------------
# FC-72  : 3M Fluorinert FC-72 is primarily perfluorohexane (C6F14).
#           CoolProp 7.2 does not include this fluid. No reliable approximation
#           exists within the standard CoolProp backend; raise explicitly.
# FC-77  : 3M Fluorinert FC-77 is a mixture of perfluorinated compounds.
#           Not available in CoolProp 7.2.
# HFE-7100: 3M Novec HFE-7100 (methoxyperfluorobutane, C5H3F9O).
#            Not available in CoolProp 7.2 (only HFE143m is present).
# Novec649: CoolProp supports this as "Novec649".

_FLUID_MAP: dict[str, str] = {
    # key (lower-case project name) : CoolProp backend name
    "water":    "Water",
    "r-123":    "R123",
    "r123":     "R123",
    "r-134a":   "R134a",
    "r134a":    "R134a",
}

# Fluids explicitly known to be unsupported in CoolProp 7.2
# (either absent entirely, or missing critical transport properties
#  such as surface tension, viscosity, or thermal conductivity)
_UNSUPPORTED_FLUIDS: dict[str, str] = {
    "fc-72":    (
        "FC-72 (perfluorohexane C6F14) is not available in CoolProp 7.2. "
        "Provide user-defined property tables or use an external source."
    ),
    "fc72":     "See 'FC-72'.",
    "fc-77":    (
        "FC-77 (3M Fluorinert mixture) is not available in CoolProp 7.2. "
        "Provide user-defined property tables or use an external source."
    ),
    "fc77":     "See 'FC-77'.",
    "hfe-7100": (
        "HFE-7100 (methoxyperfluorobutane) is not available in CoolProp 7.2. "
        "Only 'HFE143m' is present in CoolProp. "
        "Provide user-defined property tables or use an external source."
    ),
    "hfe7100":  "See 'HFE-7100'.",
    # Novec649 is present in CoolProp 7.2 but is missing surface tension,
    # dynamic viscosity, and thermal conductivity data — unusable for ONB calc.
    "novec649": (
        "Novec649 is in the CoolProp 7.2 database but lacks surface tension, "
        "viscosity, and thermal conductivity models. "
        "Provide supplementary property tables for ONB calculations."
    ),
    "fc-5112":  "See 'Novec649'.",
}

# Supported project-facing names for error messages
_SUPPORTED_NAMES = sorted(_FLUID_MAP.keys())

# Pressure limits [Pa]
_P_MIN: float = 1_000.0       # 1 kPa
_P_MAX: float = 22_064_000.0  # 22.064 MPa (water critical pressure, most conservative)

_G: float = 9.80665  # standard gravity [m/s^2]
GRAVITY: float = _G  # public alias used by other utils modules


# ---------------------------------------------------------------------------
# Custom exceptions
# ---------------------------------------------------------------------------

class UnsupportedFluidError(ValueError):
    """Raised when a fluid is not available in CoolProp 7.2."""


class PressureRangeError(ValueError):
    """Raised when input pressure is outside the valid range."""


class AboveCriticalPressureError(ValueError):
    """Raised when input pressure exceeds the fluid's critical pressure."""


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SaturationProperties:
    """Thermophysical properties at saturation for a given fluid and pressure.

    All quantities in SI units.

    Attributes
    ----------
    fluid : str
        Project-facing fluid identifier (as passed by the caller).
    P : float
        Absolute pressure [Pa].
    T_sat : float
        Saturation temperature [K].
    rho_l : float
        Saturated liquid density [kg/m^3].
    rho_v : float
        Saturated vapour density [kg/m^3].
    sigma : float
        Surface tension (liquid–vapour) [N/m].
    h_fg : float
        Latent heat of vaporisation (h_v - h_l) [J/kg].
    mu_l : float
        Dynamic viscosity of saturated liquid [Pa·s].
    k_l : float
        Thermal conductivity of saturated liquid [W/(m·K)].
    cp_l : float
        Isobaric specific heat of saturated liquid [J/(kg·K)].
    Pr_l : float
        Prandtl number of saturated liquid [—].
    nu_l : float
        Kinematic viscosity of saturated liquid (mu_l / rho_l) [m^2/s].
    """

    fluid: str
    P:     float
    T_sat: float
    rho_l: float
    rho_v: float
    sigma: float
    h_fg:  float
    mu_l:  float
    k_l:   float
    cp_l:  float
    Pr_l:  float
    nu_l:  float

    def __repr__(self) -> str:
        return (
            f"SaturationProperties("
            f"fluid={self.fluid!r}, "
            f"P={self.P:.4g} Pa, "
            f"T_sat={self.T_sat:.4f} K, "
            f"rho_l={self.rho_l:.4g} kg/m³, "
            f"rho_v={self.rho_v:.4g} kg/m³, "
            f"sigma={self.sigma:.4e} N/m, "
            f"h_fg={self.h_fg:.4e} J/kg, "
            f"mu_l={self.mu_l:.4e} Pa·s, "
            f"k_l={self.k_l:.4f} W/(m·K), "
            f"cp_l={self.cp_l:.4f} J/(kg·K), "
            f"Pr_l={self.Pr_l:.4f}, "
            f"nu_l={self.nu_l:.4e} m²/s"
            f")"
        )


# ---------------------------------------------------------------------------
# Core property function
# ---------------------------------------------------------------------------

@lru_cache(maxsize=256)
def saturation_properties(
    fluid: str,
    P: float = 101_325.0,
) -> SaturationProperties:
    """Compute saturation-state thermophysical properties using CoolProp.

    Parameters
    ----------
    fluid : str
        Project-facing fluid identifier. Case-insensitive.
        Supported: 'water', 'R-123', 'R-134a', 'Novec649'.
        Unsupported (CoolProp 7.2): 'FC-72', 'FC-77', 'HFE-7100'.
    P : float
        Absolute pressure [Pa]. Must be in [1 kPa, 22.064 MPa].

    Returns
    -------
    SaturationProperties
        Frozen dataclass with all saturation properties.

    Raises
    ------
    UnsupportedFluidError
        If the fluid is known but unavailable in CoolProp 7.2.
    ValueError
        If the fluid is completely unrecognised.
    PressureRangeError
        If P is outside [_P_MIN, _P_MAX].
    AboveCriticalPressureError
        If P exceeds the fluid's critical pressure.

    Notes
    -----
    Results are LRU-cached by (fluid, P) to avoid redundant CoolProp calls
    during batch loss-function evaluations in the PINN training loop.

    CoolProp output keys used:
        'T'       — temperature  [K]
        'D'       — density      [kg/m^3]
        'I'       — surface tension [N/m]
        'H'       — specific enthalpy [J/kg]
        'V'       — dynamic viscosity [Pa·s]
        'L'       — thermal conductivity [W/(m·K)]
        'C'       — isobaric specific heat [J/(kg·K)]
        'Prandtl' — Prandtl number [—]
    """
    fluid_key = fluid.strip().lower()

    # --- fluid validation ---
    if fluid_key in _UNSUPPORTED_FLUIDS:
        raise UnsupportedFluidError(
            f"Fluid '{fluid}' is not supported in CoolProp 7.2.\n"
            f"Reason: {_UNSUPPORTED_FLUIDS[fluid_key]}\n"
            f"Supported fluids: {_SUPPORTED_NAMES}"
        )
    if fluid_key not in _FLUID_MAP:
        raise ValueError(
            f"Unknown fluid '{fluid}'. "
            f"Supported fluids: {_SUPPORTED_NAMES}. "
            f"Unsupported (FC-72, FC-77, HFE-7100) require user-defined tables."
        )

    cp_name: str = _FLUID_MAP[fluid_key]

    # --- pressure range validation (global bound) ---
    if not (_P_MIN <= P <= _P_MAX):
        raise PressureRangeError(
            f"Pressure P={P:.4g} Pa is outside the valid range "
            f"[{_P_MIN:.4g}, {_P_MAX:.4g}] Pa."
        )

    # --- above critical pressure check (per fluid) ---
    p_crit: float = _CP.PropsSI("Pcrit", cp_name)
    if P >= p_crit:
        raise AboveCriticalPressureError(
            f"P={P:.4g} Pa exceeds the critical pressure of {cp_name} "
            f"({p_crit:.4g} Pa). Cannot compute saturation properties."
        )

    # --- CoolProp calls: liquid side (Q=0) ---
    def _liq(output: str) -> float:
        return _CP.PropsSI(output, "P", P, "Q", 0, cp_name)

    def _vap(output: str) -> float:
        return _CP.PropsSI(output, "P", P, "Q", 1, cp_name)

    T_sat = _liq("T")
    rho_l = _liq("D")
    rho_v = _vap("D")
    sigma  = _liq("I")
    h_l    = _liq("H")
    h_v    = _vap("H")
    h_fg   = h_v - h_l
    mu_l   = _liq("V")
    k_l    = _liq("L")
    cp_l   = _liq("C")
    Pr_l   = _liq("Prandtl")
    nu_l   = mu_l / rho_l

    return SaturationProperties(
        fluid=fluid,
        P=P,
        T_sat=T_sat,
        rho_l=rho_l,
        rho_v=rho_v,
        sigma=sigma,
        h_fg=h_fg,
        mu_l=mu_l,
        k_l=k_l,
        cp_l=cp_l,
        Pr_l=Pr_l,
        nu_l=nu_l,
    )


# ---------------------------------------------------------------------------
# Dimensionless-number helpers
# ---------------------------------------------------------------------------

def jacob_number(
    props: SaturationProperties,
    delta_T_sub: float,
) -> float:
    """Jacob number for subcooled pool boiling.

    Ja = (rho_l * cp_l * delta_T_sub) / (rho_v * h_fg)

    Parameters
    ----------
    props : SaturationProperties
        Saturation properties at the operating pressure.
    delta_T_sub : float
        Liquid subcooling, T_sat - T_bulk [K].  Must be >= 0.

    Returns
    -------
    float
        Jacob number [—].
    """
    if delta_T_sub < 0.0:
        raise ValueError(
            f"delta_T_sub must be >= 0 (got {delta_T_sub:.4g} K). "
            "Subcooling is defined as T_sat - T_bulk."
        )
    return (props.rho_l * props.cp_l * delta_T_sub) / (props.rho_v * props.h_fg)


def capillary_length(
    props: SaturationProperties,
    g: float = _G,
) -> float:
    """Capillary (Laplace) length scale for bubble departure.

    L_c = sqrt(sigma / (g * (rho_l - rho_v)))

    Parameters
    ----------
    props : SaturationProperties
        Saturation properties at the operating pressure.
    g : float
        Gravitational acceleration [m/s^2]. Default = 9.80665 m/s^2.

    Returns
    -------
    float
        Capillary length [m].
    """
    return math.sqrt(props.sigma / (g * (props.rho_l - props.rho_v)))


def hsu_criterion_cavity_radius(
    props: SaturationProperties,
    delta_T_wall: float,
    q_flux: float,
) -> tuple[float, float]:
    """Active nucleation cavity radius range from Hsu (1962).

    Hsu's criterion identifies the range of cavity mouth radii (r_c_min, r_c_max)
    that can sustain nucleation for given wall superheat and heat flux.

    The derivation considers the temperature profile in the thermal boundary
    layer (natural convection) and the Clausius-Clapeyron vapour equilibrium
    at the bubble tip. The exact quadratic solution is:

        B = (2 * sigma * T_sat) / (rho_v * h_fg)     [m·K]

        r_c_{min,max} = (k_l * delta_T_wall) / (2 * q_flux)
                        * (1 ± sqrt(1 - 8 * sigma * T_sat / (rho_v * h_fg^2
                                     * (k_l * delta_T_wall / q_flux))))

    where the minus sign gives r_c_min and the plus sign gives r_c_max.

    If the discriminant is negative, no cavity satisfies the criterion at the
    given conditions (returns (0.0, 0.0) with a warning embedded in the
    docstring; callers should check for this).

    Parameters
    ----------
    props : SaturationProperties
        Saturation properties at the operating pressure.
    delta_T_wall : float
        Wall superheat, T_wall - T_sat [K].  Must be > 0.
    q_flux : float
        Surface heat flux [W/m^2].  Must be > 0.

    Returns
    -------
    tuple[float, float]
        (r_c_min, r_c_max) in [m].  Both are 0.0 if no solution exists.

    References
    ----------
    Hsu, Y.Y. (1962). On the size range of active nucleation cavities on a
    heating surface. J. Heat Transfer, 84(3), 207-216.
    """
    if delta_T_wall <= 0.0:
        raise ValueError(
            f"delta_T_wall must be > 0 (got {delta_T_wall:.4g} K). "
            "Wall superheat is T_wall - T_sat."
        )
    if q_flux <= 0.0:
        raise ValueError(f"q_flux must be > 0 (got {q_flux:.4g} W/m^2).")

    # half-boundary-layer thickness scale: delta_t = k_l * delta_T_wall / q_flux
    delta_t: float = props.k_l * delta_T_wall / q_flux  # [m]

    # Hsu discriminant factor
    #   discriminant = 1 - 8 * sigma * T_sat / (rho_v * h_fg^2 * delta_t)
    # (derived by substituting Clausius-Clapeyron linearisation into the
    #  temperature boundary condition at the bubble tip at height r_c(1+cos θ),
    #  simplified for θ = 53.1° → factor 8/C_sf where C_sf ≈ 1 in Hsu's original)
    discriminant: float = (
        1.0
        - (8.0 * props.sigma * props.T_sat)
        / (props.rho_v * props.h_fg**2 * delta_t / props.cp_l)
        # Note: Hsu's quadratic contains cp_l * delta_T_wall / h_fg
        # Full exact form from Hsu (1962) eq. 13:
    )

    # Re-derive with Hsu's exact grouping (eq. 13 in the original paper):
    #   discriminant_exact = 1 - (8 * sigma * T_sat * cp_l) /
    #                             (rho_v * h_fg^2 * delta_t)
    discriminant_exact: float = (
        1.0
        - (8.0 * props.sigma * props.T_sat * props.cp_l)
        / (props.rho_v * props.h_fg**2 * delta_t)
    )

    if discriminant_exact < 0.0:
        # No active cavity exists at these conditions
        return (0.0, 0.0)

    sqrt_disc: float = math.sqrt(discriminant_exact)

    # r_c = (delta_t / 2) * (1 ± sqrt_disc)
    r_c_min: float = (delta_t / 2.0) * (1.0 - sqrt_disc)
    r_c_max: float = (delta_t / 2.0) * (1.0 + sqrt_disc)

    return (r_c_min, r_c_max)


# ---------------------------------------------------------------------------
# Module-level validation / demonstration
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    SEP = "-" * 60

    # ------------------------------------------------------------------
    # 1. Water at 1 atm — validation against known reference values
    # ------------------------------------------------------------------
    print(SEP)
    print("1. Water at 1 atm (101 325 Pa)")
    print(SEP)
    w = saturation_properties("water", P=101_325.0)
    print(w)

    TOLERANCES = {
        "T_sat":  (373.124, 0.005),   # K,     tol 0.5 %
        "rho_l":  (958.4,   0.005),   # kg/m^3
        "sigma":  (0.0589,  0.005),   # N/m
        "h_fg":   (2.257e6, 0.005),   # J/kg
    }
    print("\nValidation vs. reference values (tol = 0.5 %):")
    all_pass = True
    for attr, (ref, rel_tol) in TOLERANCES.items():
        val = getattr(w, attr)
        err = abs(val - ref) / ref
        status = "PASS" if err < rel_tol else "FAIL"
        if status == "FAIL":
            all_pass = False
        print(f"  {attr:8s}: computed={val:.5g}, ref={ref:.5g}, "
              f"rel_err={err*100:.3f}%  [{status}]")
    print("  Overall:", "ALL PASS" if all_pass else "SOME FAIL")

    # ------------------------------------------------------------------
    # 2. R-134a at 5 bar
    # ------------------------------------------------------------------
    print()
    print(SEP)
    print("2. R-134a at 5 bar (500 000 Pa)")
    print(SEP)
    r134a = saturation_properties("R-134a", P=500_000.0)
    print(r134a)

    # ------------------------------------------------------------------
    # 3. Hsu r_c range — water at 1 atm, dT_wall=10 K, q=50 kW/m^2
    # ------------------------------------------------------------------
    print()
    print(SEP)
    print("3. Hsu criterion — water at 1 atm")
    print("   delta_T_wall = 10 K,  q_flux = 50 000 W/m^2")
    print(SEP)
    r_min, r_max = hsu_criterion_cavity_radius(w, delta_T_wall=10.0, q_flux=50_000.0)
    if r_min == 0.0 and r_max == 0.0:
        print("  No active cavity exists at these conditions (negative discriminant).")
    else:
        print(f"  r_c_min = {r_min*1e6:.3f} um")
        print(f"  r_c_max = {r_max*1e6:.3f} um")
        print(f"  (physical range: 1 – 100 um)")

    # ------------------------------------------------------------------
    # 4. Dimensionless numbers — water at 1 atm, delta_T_sub = 5 K
    # ------------------------------------------------------------------
    print()
    print(SEP)
    print("4. Dimensionless helpers — water at 1 atm, delta_T_sub = 5 K")
    print(SEP)
    Ja = jacob_number(w, delta_T_sub=5.0)
    L_c = capillary_length(w)
    print(f"  Jacob number  Ja = {Ja:.4f}")
    print(f"  Capillary len L_c = {L_c*1e3:.4f} mm")

    # ------------------------------------------------------------------
    # 5. Error handling examples
    # ------------------------------------------------------------------
    print()
    print(SEP)
    print("5. Error handling")
    print(SEP)
    for bad_fluid in ["FC-72", "HFE-7100", "FC-77", "Novec649"]:
        try:
            saturation_properties(bad_fluid)
        except UnsupportedFluidError as exc:
            print(f"  UnsupportedFluidError for '{bad_fluid}': {str(exc).splitlines()[0]}")

    try:
        saturation_properties("water", P=0.5)  # below _P_MIN
    except PressureRangeError as exc:
        print(f"  PressureRangeError (P=0.5 Pa): {exc}")

    sys.exit(0 if all_pass else 1)
